-- Trouver tous les marins >= 16 ans, aptes, avec dates valides et les 4 modules : 

SELECT DISTINCT aah.ID_ADM_ADMINISTRE
FROM ADM_ADMINISTRE_HISTORIQUE aah
JOIN ESC_EPISODE_SANTE ees
    ON aah.ID_ADM_ADMINISTRE = ees.ID_ADM_ADMINISTRE
JOIN ESC_APTITUDE ea
    ON ees.ID_ESC_EPISODE_SANTE = ea.ID_ESC_EPISODE_SANTE
JOIN (
    SELECT amf_c.ID_ADM_ADMINISTRE
    FROM AMF_CANDIDAT amf_c
    JOIN AMF_ACQUISITION amf_a
        ON amf_c.ID_AMF_CANDIDAT = amf_a.ID_AMF_CANDIDAT
    WHERE amf_c.ID_AMF_CANDIDAT IN (
        SELECT amf_a2.ID_AMF_CANDIDAT
        FROM AMF_ACQUISITION amf_a2
        WHERE amf_a2.ID_AMF_MODULE_UV IN ('500014', '500015', '500016', '500016')
        GROUP BY amf_a2.ID_AMF_CANDIDAT
        HAVING COUNT(DISTINCT amf_a2.ID_AMF_MODULE_UV) = 4
    )
) candidates
    ON ees.ID_ADM_ADMINISTRE = candidates.ID_ADM_ADMINISTRE
WHERE aah.DATE_NAISSANCE <= {{age_date}}
  AND ea.DATE_FIN_VALIDITE >= {{aptitude_date}}
  AND ea.IDC_DECISION_MEDICALE = 1
ORDER BY aah.ID_ADM_ADMINISTRE;
